CREATE ROLE hollis_app
  LOGIN
  PASSWORD 'hollis_app'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS;

GRANT CONNECT ON DATABASE hollis TO hollis_app;
GRANT USAGE ON SCHEMA public TO hollis_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hollis_app;
